add error handler to cannon build process and all exported artifacts (#31)
using the cannon context, as it is being built live and after chain is
established, detailed error messages can be parsed and displayed to the
user!

here is an example of the output when I just added `revert("Its a failure")` to the sample greeter contract:

```
CannonTraceError: transaction reverted: Error("Its a failure")

  CALL greeters.greeter.setGreeting("new greeting!") => Error("Its a failure")
    STATICCALL console.log("Changing greeting from '%s' to '%s'", "Hello world!", "new greeting!")
```

notice how the error also includes the full calldata, any intermediate
contract calls (should be amazing for v2x!), and any `console.log` you
may have in your code, and any errors/revert reasons seen.

here is another example where, I add a line `uint testval = 1 / uint(0);`:

```
CannonTraceError: transaction reverted: Panic("division by zero")

  CALL greeters.greeter.setGreeting("new greeting!") => Panic("division by zero")
    STATICCALL console.log("Changing greeting from '%s' to '%s'", "Hello world!", "new greeting!")
```

custom solidity errors are also decoded:

```
CannonTraceError: transaction reverted: DummyError("custom text", "42069")

  CALL greeters.greeter.setGreeting("new greeting!") =>
DummyError("custom text", "42069")
    STATICCALL console.log("Changing greeting from '%s' to '%s'", "Hello
world!", "new greeting!")

    at handleTxnError
(/home/daniel/code/cannon/packages/builder/src/error.ts:57:11)
    at processTicksAndRejections
(node:internal/process/task_queues:95:5)
```

if the error is not able to be decoded, the original error is returned
unmodified, so you don't need to worry about it making errors harder to
read than they already are.

Unfortunately anvil does not supply information regarding the contract
source code, which means you wont see any tracing for contract internal
calls.